stages:
  - test
  - build
  - release

test:
  image: node:alpine
  stage: test

  variables:
    HTTP_PORT: 3000
    HEADLESS: "false"
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

  before_script:
    - apk add --no-cache git
    - npm install

  script:
    - npm run lint
    - npm run test

build:
  image: docker:stable
  stage: build

  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    REGISTRY: registry.gitlab.com/b256/discovery/crawler

  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com

  script:
    - docker build --pull -t $REGISTRY:$CI_COMMIT_REF_NAME .
    - docker push $REGISTRY:$CI_COMMIT_REF_NAME

release:
  image: docker:stable
  stage: release

  only:
    - master

  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    REGISTRY: registry.gitlab.com/b256/discovery/crawler

  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com

  script:
    - docker pull $REGISTRY:$CI_COMMIT_REF_NAME
    - docker tag $REGISTRY:$CI_COMMIT_REF_NAME $REGISTRY:latest
    - docker push $REGISTRY:latest
